Cats_website/config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :cats 
end

Cats_website/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

Cats_website/app/models/cat.rb
require 'action_view'
class Cat < ApplicationRecord
    ActionView::Helpers::DateHelper

    COLORS = ['brown', 'orange', 'black', 'grey']
    validates :color, inclusion: COLORS 
    SEX = ["M", "F"]
    validates :sex, inclusion: SEX 
    validates :birth_date, :color, :name, :sex, :description, presence: true



    def age
        currentTime = Date.today
        ((currentTime  - self.birth_date).to_i)/365
    end
end

Cats_website/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

Cats_website/app/controllers/cats_controller.rb
class CatsController < ApplicationController
    def index
        @cats = Cat.all 
        render :index
    end

    def show
        @cat = Cat.find_by(id: params[:id])
        if @cat
            render :show 
        else
            render :index
        end
    end

    def new 
        render :new 
    end

    def edit
      
        @cat = Cat.find_by(id: params[:id])
        render :edit
    end
end

Cats_website/app/helpers/application_helper.rb
module ApplicationHelper
end

Cats_website/app/views/cats/_form.html.erb
<h1> Edit <%= cat.name %> </h1>

<form action = "/cats" method="POST">
    <input type="hidden" name = "_method" value = "patch">
    <label for="Name">Name </label>
    <input id="Name" type="text" name="cat[name]" value="<%= cat.name %>">
    <br>
    <label for="Birthday"> Birthday </label>
    <input id="Birthday" type="date" name="cat[birth_day]" value="<%= cat.birth_date %>">
    <br>
    
    <label for="Color">Color </label>
    <select id="Color" name="cat[color]">
      
        <option value="orange" <%= cat.color == "orange" ? "selected" : "" %> >Orange</option>
        <option value="black" <%= cat.color == "black" ? "selected" : "" %> >Black</option>
        <option value="grey" <%= cat.color == "grey" ? "selected" : "" %>>Grey</option>
        <option value="brown" <%= cat.color == "brown" ? "selected" : "" %>>Brown</option>
    </select>
    <br>
    <p>Sex</p>
    <input name = "S"  type="radio" id = "M" value = "M" <%= cat.sex == "M" ? checked = "checked" : "" %>> 
    <label for="M">M</label>
    <input name = "S" type="radio" id = "F" value = "F" <%= cat.sex == "F" ? checked = "checked" : "" %>> 
    <label for="F">F</label>
    <br>

    <label for="Description">Description</label>
    <textarea name="cat[description]"><%= cat.description %></textarea>
    <br>
    <input type="submit" value="Edit cat">
</form>

Cats_website/app/views/cats/edit.html.erb
<%=render 'form', cat: @cat %>

Cats_website/app/views/cats/index.html.erb
<h1> All the Cats </h1>


<ul>
<% @cats.each do |cat| %>
    <li>
        <a href="<%=cat_url(cat)%>"> <%= cat.name%> </a>
    </li>
    <% end %>
</ul>

Cats_website/app/views/cats/new.html.erb
<%=render 'form', cat: @cat %>

Cats_website/app/views/cats/show.html.erb
<table>
    <thead>
        <tr>
            <th colspan="2">  <%= @cat.name %> </th>
        </tr>
    </thead>
    <tbody>
        <tr>
            <td>Birthday</td>
            <td><%= @cat.birth_date %></td>
        </tr>
        <tr>
            <td>Age</td>
            <td><%= @cat.age %></td>
        </tr>
        <tr>
            <td>Color</td>
            <td><%= @cat.color %></td>
        </tr>
        <tr>
            <td>Sex</td>
            <td><%= @cat.sex %></td>
        </tr>
        <tr>
            <td>Description </td>
            <td><%= @cat.description %></td>
        </tr>
    </tbody>
</table>

Cats_website/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>CatsWebsite</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>